# Test changes of this .travis.yml config before submitting them:
# http://lint.travis-ci.org/SecUpwN/Android-IMSI-Catcher-Detector

# Travis CI Settings
#-------------------

language: android
env:
  global:
# Using the new Container-Based Infrastructure
    - sudo: false
# Turning off caching to avoid caching Issues
    - cache: false
# Initiating clean Gradle output
    - TERM=dumb
# Amount of memory granted to Gradle JVM
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
# Encrypted COVERITY_SCAN_TOKEN
    - secure: "jRKgZfeAxDhqDIrySBESiij3Ot9cmVQ4CMB+IVpmf7Xjfek6By1ba7Y1lgMdLRPgvLkj3k5mMx1BMx2yeSCBp/+TZJ6Ezj3EVJ6HS2ctkAH4KzsiqlSCKiRgfOqKgzfnftCkNzXCEE3XLVLcv4iT5Ru/EBG85kEDViGrDBP+PxA="
  matrix:
    - ANDROID_TARGET=android-17  ANDROID_ABI=armeabi-v7a

before_install:
# Making sure gradlew has executable permissions
    - chmod +x gradlew

android:
  components:
# We are using the latest revision of Android SDK Tools
     - platform-tools
     - tools
     
# The BuildTools version we are using for our project
     - build-tools-21.1.1
     
# System Image we use to run emulator(s) during tests
     - sys-img-armeabi-v7a-android-17
    
  licenses:
     - 'android-sdk-license-.+'
     
# Emulator Management: Create, Start and Wait
before_script:
# Inspecting running services
     - ps auxww
     - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
     - emulator -avd test -no-skin -no-audio -no-window &
     - android-wait-for-emulator
     - adb shell input keyevent 82 &
     
script: ./gradlew connectedAndroidTest

# Coverity Scan Settings
#-----------------------

addons:
  coverity_scan:
    project:
      name: "SecUpwN/Android-IMSI-Catcher-Detector"
    notification_email: annoyed@coverity.notifications
# Scan results: http://scan.coverity.com/projects/3346
    build_command_prepend: "./gradlew clean"
    build_command: "./gradlew build"
    branch_pattern: master
